# AUTHOR:  MAWLZZ
# DATE:    22.08.23
# DESC:    FOR HOLLYPOP. 
#          EMULATES FRIENDSHIP LIGHTS 
#          Δ LIGHT A → LIGHT B
#          Δ LIGHT B → LIGHT A
# ADDED:   COLOR_MODE SELECTION
# TODO:    FIX COLOR_TEMP when light B changes and A should update - currently only RGB functions
- id: update_b_by_type
  alias: Update B by type
  trigger:
    - platform: state
      entity_id:
        - light.ENTITY_ID_OF_LIGHT_A  # Light A
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ state_attr('light.ENTITY_ID_OF_LIGHT_A', 'color_mode') == 'rgb' }}"
          sequence:
            - service: script.turn_on
              entity_id: script.copy_light_state_a_rgb
        - conditions:
            - condition: template
              value_template: "{{ state_attr('light.ENTITY_ID_OF_LIGHT_A', 'color_mode') == 'color_temp' }}"
          sequence:
            - service: script.turn_on
              entity_id: script.copy_light_state_a_color_temp

- id: update_a_by_type
  alias: Update A by type
  trigger:
    - platform: state
      entity_id:
        - light.ENTITY_ID_OF_LIGHT_B  # Light B
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ state_attr('light.ENTITY_ID_OF_LIGHT_B', 'color_mode') == 'color_temp' }}"
          sequence:
            - service: script.turn_on
              entity_id: script.copy_light_state_b_color_temp
        - conditions:
            - condition: template
              value_template: "{{ state_attr('light.ENTITY_ID_OF_LIGHT_B', 'color_mode') == 'rgb' }}"
          sequence:
            - service: script.turn_on
              entity_id: script.copy_light_state_b_rgb
